# Generated by Django 2.2.2 on 2019-06-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title ', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description ', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
