# Generated by Django 2.2.2 on 2019-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, help_text='Author', max_length=400, null=True),
        ),
    ]
