# Generated by Django 2.2.2 on 2019-06-30 21:37

from django.db import migrations

def load_booklist(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_book_author'),
    ]

    operations = [migrations.RunPython(load_booklist)]
    
