# Generated by Django 2.2.2 on 2019-06-30 21:37

from django.db import migrations

def load_booklist(apps, schema_editor):
    Book = apps.get_model('shelf', 'Book')
    Category = apps.get_model('shelf', 'Category')
    
    # Card.objects.all().delete()
    # Stack.objects.all().delete()
    category = Category(name="Fiction")
    category.save()
    filename = os.path.join(settings.BASE_DIR, 'sample_books.csv')
    with open(filename) as file:
        reader = csv.DictReader(file)
        for row in reader:
            book = Book(title=row['title'], author=row['author'], description=row['description'], url=row['url'],category=category)
            book.save()
# def delete_data(apps, schema_editor):
#     Stack = apps.get_model('core', 'Stack')
#     Card = apps.get_model('core', 'Card')
#     Card.objects.all().delete()
#     Stack.objects.all().delete()
#     ]    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_book_author'),
    ]

    operations = [migrations.RunPython(load_booklist)]
    
