# Generated by Django 2.2.2 on 2019-06-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20190630_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category for this book', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(help_text='Book url', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Book title', max_length=200),
        ),
    ]
