# Generated by Django 2.2.2 on 2019-06-30 22:37

from django.db import migrations
from django.conf import settings
import os
import csv

def load_booklist(apps, schema_editor):
    Book = apps.get_model('shelf', 'Book')
    Category = apps.get_model('shelf', 'Category')
    
    category = Category(name="Fiction")
    category.save()
    filename = os.path.join(settings.BASE_DIR, 'sample_books.csv')
    with open(filename) as file:
        reader = csv.DictReader(file)
        for row in reader:
            book = Book(title=row['title'], author=row['author'], description=row['description'], url=row['url'])
            book.save()
   


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20190630_1822'),
    ]

    operations = [migrations.RunPython(load_booklist)]

